apiVersion: v1
kind: Pod
metadata:
  name: uploader-pod
spec:
  containers:
  - name: uploader
    image: busybox
    command: ["sh", "-c", "echo 'This file is stored in PV!' > /mydata/file.txt && sleep 3600"]
    volumeMounts:
    - name: storage
      mountPath: /mydata
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: my-pvc
